version: '2'
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        depends_on:
            - db
        command: ['sh', '-c', '(python app.py; npm run dev)']
    db:
        image: postgres
